### ISSUE TITLE
Readme examples normalized with ? no longer parse

### ISSUE THREAD

**Issue by ankane** [pganalyze/pg_query#276]
Hi, some of the examples in the readme no longer parse (and should probably be removed) since support for `?` was dropped in libpg_query 14-3.0.0, like:

```ruby
PgQuery.parse("SELECT ? FROM x WHERE y = ?")
```

Also, the changelog dates seem a bit off compared to [RubyGems](https://rubygems.org/gems/pg_query/versions).

**Comment by lfittl** [comment]
@ankane Good catch! We no longer support that syntax since the Postgres versions that generated this in pg_stat_statements are now EOL. I'll make a PR to update the README.

The changelog dates between CHANGELOG and RubyGems are different since they are technically separate processes on our end (and we had a delay in publishing the latest release 4.2.0). We may make the release automatic in the future, but currently its an explicit step.

**Comment by ankane** [comment]
Thanks @lfittl!

fwiw, the changelog dates for the latest two releases have the wrong year, but in general, I think it'd be helpful for users if it matched the date it was released on RubyGems (+/- 1 day for time zone differences).
