### ISSUE TITLE
Deparse with indentation?

### ISSUE THREAD

**Issue by Willianvdv** [pganalyze/pg_query#75]
For a while now we're looking for a gem that can format a given (PostgreSQL) query with indentation. There are a couple of them out there, but they can't handle PostgreSQL specifics, have errors in the outputted SQL or can't be found by me.

So my question, do you think it's feasible to use/extend your gem to parse and deparse with indentation? Or even better, did someone already did this?

**Comment by lfittl** [comment]
@Willianvdv Can you clarify a bit what you mean by "with indentation" - do you mean essentially an opinionated deparse that formats the query a certain way?

As far as I know nobody has done it yet on the basis of this gem (and not familiar with any other efforts besides generic ones that don't support all Postgres syntax), but it wouldn't be too difficult to implement.

A good start for that discussion would maybe be if you can provide an example of what you think would make sense as output rules? I'm thinking we could teach the deparser different styles of output that can be set optionally (i.e. default to the current minimal formatting, but ship one or more better looking output options)

**Comment by Willianvdv** [comment]
Yeah! I'm not sure what format flavors there are in the SQL world, but the first hit in Google brought me to http://www.sqlstyle.guide/ which describes some best practices how to make your query readable. I can try to add an optional style parameter to deparse to use this style guide.

**Comment by lfittl** [comment]
@Willianvdv Sounds good - a PR would be very welcome!

**Comment by lfittl** [comment]
Closing this, since the issue has become stale, and the deparser-based efforts described here unfortunately didn't pan out at the time.

If one were to attempt this, please be aware that the deparser has moved to the C library (context: https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser#turning-parse-trees-back-into-sql-using-a-deparser), and it would need to be implemented there.

That said, an alternative method would be to utilize the new scanner method to guide whitespace formatting: https://github.com/pganalyze/pg_query/blob/main/spec/lib/scan_spec.rb

(i.e. don't parse and deparse at all, just use the scanner to understand where keywords are located in the source string, and then format based on that)
